# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (07:00 Saturday)
  schedule: [{ cron: "12 7 * * 6" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: thorpelawrence
          repositories_affiliations: owner
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_followup: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_ignored: html,css,tex
          plugin_languages_skipped: quizics,DrawingArea,ImageViewer
          plugin_lines: yes
          plugin_pagespeed: yes
          plugin_pagespeed_url: .user.website
